//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenScan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStatus
    {
        public string email { get; set; }
        public string paymentStatus { get; set; }
        public string dateTime { get; set; }
    }
}
